
CREATE DATABASE IF NOT EXISTS VITRINE_NORMITH DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE VITRINE_NORMITH;

CREATE TABLE IF NOT EXISTS USUARIOS (
  ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL UNIQUE,
  SENHA VARCHAR(255) NOT NULL,
  TIPO ENUM('admin', 'colaborador') DEFAULT 'admin',
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORIAS (
  ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL UNIQUE,
  DESCRICAO TEXT,
  ICONE VARCHAR(50),
  IMAGEM_URL VARCHAR(255),
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PRODUTOS (
  ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(150) NOT NULL,
  DESCRICAO TEXT NOT NULL,
  PRECO DECIMAL(10,2) NOT NULL,
  IMAGEM_URL VARCHAR(255) NOT NULL,
  ESTOQUE INT DEFAULT 1,
  MADEIRA VARCHAR(100),
  PESO VARCHAR(50),
  TAMANHO VARCHAR(50),
  VIROLA VARCHAR(50),
  CATEGORIA_ID INT,
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID_CATEGORIA) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ORCAMENTOS (
  ID_ORCAMENTO INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL,
  WHATSAPP VARCHAR(20) NOT NULL,
  MENSAGEM TEXT NOT NULL,
  PRODUTO_DESEJADO_ID INT DEFAULT NULL, -- Opicional do front, talvez vamos excluir
  OBSERVACOES TEXT, -- Para o admin anotar algo sobre o contato do cliente
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (PRODUTO_DESEJADO_ID) REFERENCES PRODUTOS(ID_PRODUTO) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CONFIGURACOES_SITE (
  CHAVE VARCHAR(100) PRIMARY KEY,
  VALOR TEXT NOT NULL,
  ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS GALERIA_SITE (
  ID_IMAGEM INT AUTO_INCREMENT PRIMARY KEY,
  IMAGEM_URL VARCHAR(255) NOT NULL,
  ORDEM INT DEFAULT 0
) ENGINE=InnoDB;
